spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/seoblog

jwt:
  token:
    header: Authorization
    role: USER
    issuer: hclee@gmail.com
    clientId: hclee
    clientSecret: hclee
    expirySeconds: 86400